services:
  # Web Service - FastAPI application
  - type: web
    name: langgraph-training-api
    env: docker
    region: singapore
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .

    # Health check
    healthCheckPath: /health

    # Environment variables
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: SLACK_TOKEN
        sync: false
      - key: SLACK_SIGNING_SECRET
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: NOTION_TOKEN
        sync: false
      - key: JIRA_TOKEN
        sync: false
      - key: JIRA_SERVER
        sync: false
      - key: JIRA_EMAIL
        sync: false
      - key: GOOGLE_CLOUD_PROJECT
        sync: false
      - key: GOOGLE_CREDENTIALS_PATH
        value: /app/secrets/google_credentials.json
      - key: GOOGLE_TOKEN_PATH
        value: /app/secrets/google_token.json
      - key: APP_NAME
        value: LangGraph Training API
      - key: DEBUG
        value: false

    # Auto-deploy from main branch
    autoDeploy: true
