"""定数定義"""

# LLM設定
DEFAULT_TEMPERATURE = 0.7
DEFAULT_MAX_TOKENS = 1000

# RAG設定
DEFAULT_COLLECTION_NAME = "default_collection"
DEFAULT_TOP_K = 5
DEFAULT_CHUNK_SIZE = 500
DEFAULT_CHUNK_OVERLAP = 50

# 検索設定
DEFAULT_SEMANTIC_WEIGHT = 0.7
DEFAULT_BM25_WEIGHT = 0.3

# コンテキスト管理
DEFAULT_MAX_HISTORY_TURNS = 3
DEFAULT_CONTEXT_WINDOW_SIZE = 4000

# MCP設定
MCP_DEFAULT_TIMEOUT = 30
MCP_MAX_RETRIES = 3
